version: '3'

services:
  ####################################
  #   Set up server
  ####################################
  server:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/tmp
